name: Lint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint with ruff
      run: |
        ruff check --output-format=github socialmediaapi
    - name: Test with pytest
      run: |
        pytest socialmediaapi/tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=socialmediaapi --cov-report=term-missing:skip-covered | tee pytest-coverage.txt
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: .junit/test-results.xml