name: Lint and Test

on: [push]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint with ruff
      run: |
        ruff check --output-format=github socialmediaapi
    - name: Test with pytest
      run: |
        pytest socialmediaapi/tests/ --cov=socialmediaapi
